name: LCC Menu Automation

on:
  workflow_dispatch:
  schedule:
    - cron: '0 19 * * *'

jobs:
  capturar-menu:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - name: Descargar repo
        uses: actions/checkout@v5

      - name: Instalar Node
        uses: actions/setup-node@v5
        with:
          node-version: '20'

      - name: Instalar dependencias
        run: npm install

      - name: Instalar navegador Playwright
        run: npx playwright install --with-deps chromium

      - name: Ejecutar captura
        run: node menu.js
